In [9]:
import pandas as pd
import os
import pydicom
import numpy as np
import cv2
from CNN import CNN
import torch
from preprocessing import transform_to_hu,get_mask,preprocess_images
import torch.nn as nn

In [10]:


support_images = []
support_labels = []

dicom_folder = 'C:/Users/Nimesha/Documents/MSC_RESEARCH/IMAGES/Support_Set'
dicom_query = 'C:/Users/Nimesha/Documents/MSC_RESEARCH/Implementation/Prediction/data'
# Load and preprocess the DICOM images
for root, dirs, files in os.walk(dicom_folder):
    for file in files:
        file_path = os.path.join(root, file)
        dicom_image = pydicom.dcmread(file_path)
        image = np.array(dicom_image.pixel_array)

        cleaned_image = preprocess_images(image,dicom_image)
        masked_img=get_mask(file_path,plot_mask=True,return_val=True)
        
        mask_on_orginal = cleaned_image * masked_img
        mask_on_orginal = cv2.resize(mask_on_orginal, (224, 224))
        
        image = mask_on_orginal.astype('float32')
        image = np.expand_dims(image, axis=0)
        
        image = torch.from_numpy(image)

        print(type(image))
   
        label_ch = file[0]
        print(label_ch)
        print(image)
        if label_ch =='A' :
            label=0
        elif label_ch =='B':
            label=1
        elif label_ch =='G':  
            label=2
        elif label_ch =='E':
            label=3 
        else : label=4
        
        label = torch.tensor(label, dtype=torch.int64)
        
        support_images.append(image)
        support_labels .append(label)
        
support_images = torch.stack(support_images)
support_labels = torch.stack(support_labels)


100%|██████████| 4/4 [00:00<?, ?it/s]


<class 'torch.Tensor'>
A
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 3/3 [00:00<00:00, 3009.55it/s]


<class 'torch.Tensor'>
A
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<00:00, 2007.80it/s]


<class 'torch.Tensor'>
A
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
A
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<00:00, 2008.77it/s]


<class 'torch.Tensor'>
A
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
B
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 6/6 [00:00<00:00, 3010.63it/s]


<class 'torch.Tensor'>
B
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
B
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
B
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
B
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 3/3 [00:00<00:00, 3011.71it/s]


<class 'torch.Tensor'>
E
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<00:00, 2004.93it/s]


<class 'torch.Tensor'>
E
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
E
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 4/4 [00:00<00:00, 4014.65it/s]


<class 'torch.Tensor'>
E
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<00:00, 2006.36it/s]


<class 'torch.Tensor'>
E
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 10/10 [00:00<00:00, 5016.51it/s]


<class 'torch.Tensor'>
G
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
G
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
G
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
G
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


100%|██████████| 2/2 [00:00<?, ?it/s]


<class 'torch.Tensor'>
G
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


In [11]:
query_images = []

for root, dirs, files in os.walk(dicom_query):
    for file in files:
        file_path = os.path.join(root, file)
        dicom_image = pydicom.dcmread(file_path)
        image = np.array(dicom_image.pixel_array)

        cleaned_image = preprocess_images(image,dicom_image)
        masked_img=get_mask(file_path,plot_mask=True,return_val=True)
    
        mask_on_orginal = cleaned_image * masked_img
        mask_on_orginal = cv2.resize(mask_on_orginal, (224, 224))
       
        image = mask_on_orginal.astype('float32')
        image = np.expand_dims(image, axis=0)
       
        image = torch.from_numpy(image)

        query_images.append(image)


query_images = torch.stack(query_images)
print(type(query_images))


RuntimeError: stack expects a non-empty TensorList

In [ ]:
class PrototypicalNetworks(nn.Module):
    def __init__(self, backbone: nn.Module):
        super(PrototypicalNetworks, self).__init__()
        self.backbone = backbone

    def forward(
        self,
        support_images: torch.Tensor,
        support_labels: torch.Tensor,
        query_images: torch.Tensor,
    ) -> torch.Tensor:
        """
        Predict query labels using labeled support images.
        """
        # Extract the features of support and query images
        z_support = self.backbone.forward(support_images)
        z_query = self.backbone.forward(query_images)


        
        
        # Infer the number of different classes from the labels of the support set
        n_way = len(torch.unique(support_labels))
        
      
        # Prototype i is the mean of all instances of features corresponding to labels == i
        z_proto = torch.cat(
            [
                
                (z_support[torch.nonzero(support_labels == label)].mean(0)).round()
                for label in range(n_way) 
            ]
        )
         
        print(z_proto)


    
        # Compute the euclidean distance from queries to prototypes
        dists = torch.cdist(z_query, z_proto)
   

        # And here is the super complicated operation to transform those distances into classification scores!
        scores = -dists
        print(type(scores))
        return scores

In [ ]:
convolutional_network = CNN()
model = PrototypicalNetworks(convolutional_network)
model.load_state_dict(torch.load('model.pth'))

model.eval()

PrototypicalNetworks(
  (backbone): CNN(
    (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (fc1): Linear(in_features=100352, out_features=256, bias=True)
    (fc2): Linear(in_features=256, out_features=10, bias=True)
  )
)

In [ ]:

def model_run():
    example_scores = model(
        support_images,
        support_labels,
        query_images,
    ).detach()
    print(example_scores.data)
    _, example_predicted_labels = torch.max(example_scores.data, 1)

    return example_predicted_labels

    

tensor([[ 162., -149., -168.,  156., -141.,   41., -158.,   -9.,  -16., -171.],
        [ -35.,   20.,  -49.,  191.,  -66.,  385., -392.,  -67.,  -31., -179.],
        [ 309., -328., -273.,  137., -237.,   76., -210.,  -67.,   75., -309.],
        [  85.,  -91., -264.,  104., -120.,  426., -402., -131.,    0., -233.]],
       grad_fn=<CatBackward0>)
<class 'torch.Tensor'>
tensor([[-141.9427, -611.1415, -381.9800, -591.4735],
        [ -90.9699, -558.1661, -285.1026, -498.4711],
        [-452.0826, -281.4464, -559.9603, -381.7710]])
tensor([0, 0, 1])
